services:
  db:
    image: postgres:18

    env_file:
      - .env

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - db_data:/var/lib/postgresql/18/docker

    healthcheck:
      test: ["CMD-SHELL", "psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'select 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  db_data:
