from decimal import Decimal
from typing import Annotated

from fastapi import FastAPI, HTTPException, Query

from marketdata.api.schemas import (
    Candle,
    CandlePage,
    DownloadRequest,
    DownloadStatus,
    Interval,
)
from marketdata.config import load_settings
from marketdata.db.connection import check_connection

app = FastAPI()


@app.get("/health")
def health():
    if not check_connection(load_settings()):
        raise HTTPException(status_code=503, detail="database unavailable")

    return {"status": "UP"}


@app.get("/v1/candles")
async def candles(
    symbol: Annotated[str, Query()],
    interval: Annotated[Interval, Query()],
    start_time: Annotated[int, Query(ge=0)],
    end_time: Annotated[int, Query(ge=0)],
    limit: Annotated[int | None, Query(ge=1, le=1000)] = 100,
    cursor: Annotated[str | None, Query()] = None,
) -> CandlePage:
    if end_time <= start_time:
        raise HTTPException(
            status_code=422, detail="end_time must be greater than start_time"
        )

    candle = make_fake_candle()
    candle_page = CandlePage(data=[candle])
    return candle_page


@app.post("/v1/downloads", status_code=201)
async def download(request: DownloadRequest) -> DownloadStatus:
    # Stub: the real id will be generated by the database in phase 4.
    return make_fake_download_status(job_id=0)


@app.get("/v1/downloads/{job_id}")
async def download_status(
    job_id: int,
) -> DownloadStatus:
    # Stub: there is no database yet, so a negative id stands in for
    # "not found". In phase 4 this becomes a query to download_jobs.
    if job_id < 0:
        raise HTTPException(status_code=404, detail="job not found")

    return make_fake_download_status(job_id=job_id)


def make_fake_candle() -> Candle:
    return Candle(
        open_time=1735689600000,
        open=Decimal("93500.10"),
        high=Decimal("93610.55"),
        low=Decimal("93480.00"),
        close=Decimal("93590.25"),
        volume=Decimal("12.34567"),
        close_time=1735689659999,
        quote_volume=Decimal("1154938.27"),
        trades=1543,
        taker_buy_base_volume=Decimal("6.12345"),
        taker_buy_quote_volume=Decimal("572847.91"),
    )


def make_fake_download_status(job_id: int) -> DownloadStatus:
    return DownloadStatus(
        id=job_id,
        status="pending",
        error=None,
    )
